---
- hosts: all 
  handlers:
   - name: restart apache
     service:
       name: apache2
       state: restarted
     become: yes
  tasks:
   - name: 'Instalando dependências do sistema operacional'
     apt: 
       name: ['php', 'apache2', 'libapache2-mod-php', 'php-gd', 'mariadb-server', 'php-mysql','pip']
       state: latest
     become: yes

   - name: 'Instalando dependências do python'
     pip:
       name: PyMySQL
       state: present

   - name: 'Criando o banco'
     mysql_db:
        name: wordpress_db
        login_user: root
        login_password: "password"
        state: present
     become: true

   - name: Create database user with name 'bob' and password '12345' with all database privileges
     mysql_user:
        login_user: root
        login_password: "password"
        name: bob
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present   

   - name: Baixando arquivo de instalação do Wordpress
     get_url:
      url: 'http://wordpress.org/latest.tar.gz'
      dest: '/tmp/wordpress.tar.gz'

   - name: 'Descompacta o wordpress'
     unarchive:
       src:  '/tmp/wordpress.tar.gz'
       dest: /var/www
       remote_src: yes
     become: yes

   - name: 'Copiando arquivo necessário'
     copy:
      src: '/var/www/wordpress/wp-config-sample.php'
      dest: /etc/sudoers.edit
      remote_src: yes
     become: yes
    
   - name: 'Configura o wp-config com as entradas do banco de dados'
     replace:
       path: '/var/www/wordpress/wp-config-sample.php'
       regexp: "{{ item.regex }}"
       replace: "{{ item.value }}"
     with_items:
     - { regex: 'database_name_here', value: 'wordpress_db'}
     - { regex: 'username_here', value: 'bob'}
     - { regex: 'password_here', value: '12345'}
     become: yes

   - name: 'Configura Apache para servir o Wordpress'
     copy:
       src: 'files/000-default.conf'
       dest: '/etc/apache2/sites-available/000-default.conf'
     become: yes
     notify:
      - restart apache

