---
- hosts: database
  handlers:
   - name: restart mysql
     service:
        name: mysql
        state: restarted
     become: yes

  tasks:

   - name: 'Instalando dependências do sistema operacional'
     apt: 
       name: ['mariadb-server', 'pip', python3-mysqldb, mariadb-client]
       state: latest
     become: yes

   - name: 'Criando o banco de dados wordpress_db'
     mysql_db:
        name: wordpress_db
        login_user: root
        login_password: "Cur1@9"
        state: present
     become: true   

   - name: 'Criando usuário do banco de dados wordpress'
     mysql_user:
        login_user: root
        login_password: "Cur1@9"
        name: bob
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present 
        host: "{{ item }}"
     become: true   
     with_items:
      - 'localhost'
      - '127.0.0.1'
      - '192.168.10.137'
      - '192.168.10.140'
   - name: 'Configurando conexões remotas'
     copy:
       src: 'files/50-server.cnf'
       dest: '/etc/mysql/mariadb.conf.d/50-server.cnf'
     notify:
      - restart mysql
     become: true   
 
- hosts: wordpress 
  handlers:
   - name: restart apache
     service:
       name: apache2
       state: restarted
     become: yes
  tasks:
   - name: 'Instalando dependências do sistema operacional'
     apt: 
       name: ['php', 'apache2', 'libapache2-mod-php', 'php-gd', 'pip']
       state: latest
     become: yes

   - name: 'Instalando dependências do python'
     pip:
       name: PyMySQL
       state: present

   - name: Baixando arquivo de instalação do Wordpress
     get_url:
      url: 'http://wordpress.org/latest.tar.gz'
      dest: '/tmp/wordpress.tar.gz'

   - name: 'Descompacta o wordpress'
     unarchive:
       src:  '/tmp/wordpress.tar.gz'
       dest: /var/www
       remote_src: yes
     become: yes

   - name: 'Copiando arquivo necessário'
     copy:
      src: '/var/www/wordpress/wp-config.php'
      dest: /etc/sudoers.edit
      remote_src: yes
     become: yes
    
   - name: 'Configura o wp-config com as entradas do banco de dados'
     replace:
       path: '/var/www/wordpress/wp-config-sample.php'
       regexp: "{{ item.regex }}"
       replace: "{{ item.value }}"
     with_items:
     - { regex: 'database_name_here', value: 'wordpress_db'}
     - { regex: 'username_here', value: 'bob'}
     - { regex: 'password_here', value: '12345'}
     - { regex: 'localhost', value: '192.168.10.101'}
     become: yes

   - name: 'Configura Apache para servir o Wordpress'
     copy:
       src: 'files/000-default.conf'
       dest: '/etc/apache2/sites-available/000-default.conf'
     become: yes
     notify:
      - restart apache

