---
- name: 'Baixando arquivo de instalação do Wordpress'
  get_url:
   url: 'http://wordpress.org/latest.tar.gz'
   dest: '/tmp/wordpress.tar.gz'
  become: true

- name: 'Descompactando arquivos do Wordpress'
  unarchive:
    src:  '/tmp/wordpress.tar.gz'
    dest: /var/www/
    remote_src: yes
  become: true

- name: 'Copiando arquivo necessário'
  copy:
     src: "{{wp_installation_dir}}/wp-config-sample.php"
     dest: "{{wp_installation_dir}}/wp-config.php"  
     remote_src: yes
  become: true

- name: 'Configurando a conexão com o banco'
  replace:
    path: "{{wp_installation_dir}}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
  - { regex: 'database_name_here', value: "{{ wp_db_name }}"}
  - { regex: 'username_here', value: "{{ wp_username }}"}
  - { regex: 'password_here', value: "{{wp_user_password}}"}
  - { regex: 'localhost', value: "{{wp_db_ip}}"}
  become: true

- name: 'Ajustando configurações do apache'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: true
  notify:
  - restart apache
