---
- name: 'Instalando dependências do sistema operacional'
  apt: 
    name: ['mariadb-server', 'pip', python3-mysqldb, mariadb-client]
    state: latest
  become: true

- name: 'Criando o banco de dados "{{ wp_db_name }}"'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    login_password: "Cur1@9"
    state: present
  become: true   

- name: 'Criando usuário do banco de dados wordpress'
  mysql_user:
    login_user: root
    login_password: "Cur1@9"
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present 
    host: "{{ item }}"
  become: true   
  with_items:
  - "{{ wp_host_ip }}"
- name: 'Configurando conexões remotas'
  copy:
    src: 'files/50-server.cnf'
    dest: '/etc/mysql/mariadb.conf.d/50-server.cnf'
  notify:
  - restart mysql
  become: true   