---
- name: Alterando o hostname
  hostname:
    name: web-01
  become: true

- name: 'Instalando pacotes necessários'
  apt: 
      name: ['php', 'apache2', 'libapache2-mod-php', 'php-gd', 'pip', php-mysqli]
      state: latest
  become: true

- name: 'Instalando dependências do python'
  pip:
    name: PyMySQL
    state: present


